version: 2

references:
  node: &node
    docker:
      - image: circleci/node:10-stretch

  master_branch: &master_branch
    filters:
      branches:
        only:
          - master

  not_master_branch: &not_master_branch
    filters:
      branches:
        ignore:
          - master

jobs:
  setup-and-build:
    <<: *node
    steps:
        - checkout
        - run: make setup
        - run: make build
        - persist_to_workspace:
            root: .
            paths:
              - Makefile
              - build
              - src
              - public

  deploy-dev:
    <<: *node
    steps:
        - attach_workspace:
            at: .
        - add_ssh_keys:
            fingerprints:
              - "50:7f:39:f8:35:c1:6b:82:95:3f:e0:37:a7:c6:9e:93"
        - run: APP=seb-kade-stg make deploy

  deploy-prod:
    <<: *node
    steps:
        - attach_workspace:
            at: .
        - add_ssh_keys:
            fingerprints:
              - "50:7f:39:f8:35:c1:6b:82:95:3f:e0:37:a7:c6:9e:93"
        - run: make deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup-and-build
      - deploy-dev:
          <<: *not_master_branch
          requires:
            - setup-and-build
      - unlock-prod-deploy:
          <<: *master_branch
          type: approval
          requires:
            - setup-and-build
      - deploy-prod:
          <<: *master_branch
          requires:
            - unlock-prod-deploy
